# 模块module （施工中）

一个`.py`文件，就是一个模块module，里面的函数、变量等等，可以被其他代码所调用。


## 引入模块

先引入python自带的模块。例如用于数学运算的`math`，其中有大量函数，例如开平方根`sqrt`就在其中。


注：math模块下的全部内容，见python文档：https://docs.python.org/zh-cn/3.8/library/math.html

### import

```
import <模块名>
import <模块名> as <简称>

```

注意：只要import一次，即可一直使用。一般我们可以放在代码的最前面。

我们可以用`<模块名>.<函数名/变量名>`来调用里面的函数或者变量，例如我们要调用`math`模块下的平方根`sqrt()`。


此时，模块内部的所有东西（函数、变量等），都必须通过`<模块名>.`来调用。


```{python}
import math
print(math.sqrt(4))
```
或者`math`中的圆周率。

```{python}
print(math.pi)
```
也可以采用简称或者缩写，例如想把math缩写成m
```{python}
import math as m
print(m.sqrt(4))
```

### 引入到当前名字空间

这种方法让模块内部的函数或者变量名，直接出现在当前名字空间中（调用的使用不用再挂着模块的名字）。如果这个模块下的某些东西特别常用，这样可以少打一些字


引入方法。
```
from <模块名> import <函数/变量名> as 简称

```

还是引入math中的开平方函数`sqrt`，可能你的代码中使用特别多，所以懒得打`math.sqrt()`，只想打`sqrt()`

同样，import一次，后续即可一直使用。


```{python}
from math import sqrt
print(sqrt(9))
print(sqrt(4))
```


还可以一次性引入模块下的所有名字

```
from <模块名> import *

```
这样你引用模块下的所有对象，都不必通过模块名来调用。


`r red("注意：")``这种方式不推荐。引入大量的你可能用不到，甚至不知道存在的东西，不是一个好习惯。

## Python常用模块

### os模块

详细内容请参与官方文档：

https://docs.python.org/zh-cn/3/library/os.html

首先要import一下
```{python}
import os
```

1. 列出目录

```{python}
os.listdir(".")
```


### time模块


### str模块


### math模块










## 自定义模块


要完成一个特定的项目，你可能要写不计其数代码，没有理由把这么多代码都放在一个`.py`文件下。

一般可以把相关的代码，放在一个`.py`文件中，然后在其他文件里用模块的方式调用。


例如，我们前面写过一个`add`函数，可以把2个数相加。


```{python}
def add(x,y):
  return x + y

print(add(1,2))
```

也写过一个翻倍函数
```{python}
def do_double(x):
  return x * 2

print(do_double(2))
```

这2个函数，显然都可以归类为计算函数，我们把中2个函数放到一个专门的文件中，例如`my_calc.py`


文件`my_calc.py`的内容。

```{python}
def add(x,y):
  return x + y

def do_double(x):
  return x * 2
```


在我们后续的任务中，如果要调用这2个函数，就可以用import


```{python}
import my_calc

print(my_calc.add(1,2))

```

当然，如简称、直接导入名称等等，和前述一样。


以后，你就可以按照你自己逻辑，如同类的函数、数据，完全特定任务需要的组件等等，来组织自己的模块。

按逻辑把你的代码分类组织，是一个好习惯。



## 包package

多个模块，可以组成一个包。（略）






